### ISSUE TITLE
Small typo mistake in README.md

### ISSUE THREAD

**Issue by minhvo-dev** [fullstack-hy2020/rate-repository-api#1]
In Authorization section, the document says: "If you performed **step 3**. in the "Getting started" section, users "kalle", "elina" and "matti" all have the password "password"." 
In my case, provided user credentials are available after executing **Step 5** (optional), not Step 3. I tried to follow all step except step 5, the result was empty when I executed a query to list all users in GraphQL playground.

**Comment by Kaltsoon** [comment]
That's true, thanks for pointing this out!
