### ISSUE TITLE
sqlite3@5.0.1 does not include binaries

### ISSUE THREAD

**Issue by MikeVedsted** [fullstack-hy2020/rate-repository-api#2]
sqlite3@5.0.1 does not include binaries, causing the the install script to fail on many machines. 
Rolling back to 5.0.0 or upgrading to 5.0.2 will solve the issue. 

More context: https://github.com/mapbox/node-sqlite3/issues/1424

**Comment by Kaltsoon** [comment]
Thanks for the heads up, I updated the sqlite version!
