### ISSUE TITLE
macOS Monterey port 5000 issue

### ISSUE THREAD

**Issue by mmatila** [fullstack-hy2020/rate-repository-api#6]
Apparently port 5000 is already in use in some of the newer macOS versions. Maybe add a little heads up in the README for these cases? ex.

You can change the port by:
1. Adding ```PORT=<PORTNUMBER>``` in the ```.env``` file. ```PORT=5001``` should work just fine
or
2. Changing the value of ```API_PORT``` in the ```config.js``` file

Change the Authorization callback URL to have the new port value.

**Comment by mluukkai** [comment]
this issue is now linked to README
